# Generated by Django 4.0.1 on 2022-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "Qilinishi kerak bo'lgan ishlar!",
            },
        ),
    ]
