# Generated by Django 4.0.1 on 2022-02-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_todo_date_alter_todo_status_alter_todo_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name="Ma'lumot")),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
